# Generated by Django 3.0.4 on 2020-03-24 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cont',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=31)),
                ('data_nasterii', models.DateField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Postare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titlu', models.CharField(max_length=255)),
                ('data_p', models.DateTimeField()),
                ('autor', models.CharField(max_length=31)),
            ],
        ),
        migrations.CreateModel(
            name='Comentariu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_ora', models.DateTimeField()),
                ('continut', models.CharField(max_length=3000)),
                ('cont', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_tema.Cont')),
                ('postare', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_tema.Postare')),
            ],
        ),
    ]
