# Generated by Django 3.0.4 on 2020-03-25 00:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_tema', '0002_auto_20200324_2329'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='continut',
            field=models.CharField(default='gol', max_length=3000),
        ),
        migrations.AlterField(
            model_name='comment',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='app_tema.Account'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='continut',
            field=models.CharField(default='gol', max_length=1000),
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='app_tema.Post'),
        ),
    ]
