# Generated by Django 3.0.4 on 2020-03-28 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tema', '0003_auto_20200325_0002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='account',
        ),
        migrations.AddField(
            model_name='comment',
            name='nume_cont',
            field=models.CharField(default='no name', max_length=31),
        ),
        migrations.DeleteModel(
            name='Account',
        ),
    ]
